#!/bin/sh

# technical copypasta from https://github.com/angular/material2/wiki/Pre-commit-hook-for-linters

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'


# =========================== forbid pushing to master ===========================
# while read local_ref local_sha1 remote_ref remote_sha1
# do
#   if [[ "${remote_ref##refs/heads/}" = "master" ]]; then
#     echo "Do not push to master branch!!!"
#     exit 1
#   fi
# done

# ================================================================================

echo "Running Linters:"

# Run tslint and get the output and return code
eslintCheck=$(npm run eslint)
ret_code=$?

# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
	printf "\n${RED}eslint:check failed:${NC}"
	echo "$eslintCheck\n"
	pass=false
else
	printf "${GREEN}eslint:check passed.${NC}\n"
fi

# If there were no failures, it is good to commit
if $pass; then
	exit 0
fi

exit 1
